version: '3.8'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dofus-tools-api-dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dofus-tools
    ports:
      - "5436:5432"

  db_migration:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: runtime-db-migration
    image: dofus-tools-api:latest-db-migration
    depends_on:
      - db
    env_file:
      - src/Dofus.Tools.Api/.env
    environment:
      ConnectionStrings__AppDatabase: "User ID =dofus-tools-api-dev;Password=password;Server=db;Port=5432;Database=dofus-tools;Pooling=true;"

  api:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: runtime
    image: dofus-tools-api:latest
    depends_on:
      - db
    ports:
      - "5004:80"
    env_file:
      - src/Dofus.Tools.Api/.env
    environment:
      ConnectionStrings__AppDatabase: "User ID =dofus-tools-api-dev;Password=password;Server=db;Port=5432;Database=dofus-tools;Pooling=true;"