name: Docker Image CI

on:
  push:
    branches: [ main , develop , release ]
  pull_request:
    branches: [ main , develop ]
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: build application
        uses: docker/build-push-action@v2
        with:
          file: src/Dockerfile
          target: build
      -
        name: test application
        uses: docker/build-push-action@v2
        with:
          file: src/Dockerfile
          target: test
      -
        name: publish application
        # Develop branch only
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          file: src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
      
 

    

