name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Application
      run: docker build -t dofus-tools-api-ci -f src/Dockerfile . --target build
      
    - uses: actions/checkout@v2
    - name: Test Application
      run: docker build -t dofus-tools-api-ci-test -f src/Dockerfile . --target test

